soad-main/cart/urls.py
from django.urls import path, include
from .import views
from django.conf.urls import url

app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart-detail/',views.cart_detail,name='cart_detail'),
    path('remove/<int:id>/',views.cart_remove, name='item_decrement'),
]

soad-main/soad/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views as main_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/',include('orders.urls')),
    path('profile/',main_views.profile,name='profile'),
    path('edit_profile/', main_views.edit_profile, name='edit_profile'),
    path('shop', main_views.shop, name="shop"),
    path('mycourses', main_views.mycourses, name="mycourses"),
    path('product/<int:id>', main_views.single_product, name='shopitem'),
    path('coursedetail/<int:id>', main_views.coursedetail, name='coursedetail'),
    path('v1/<int:id>', main_views.video1, name='v1'),
    path('v2/<int:id>', main_views.video2, name='v2'),
    path('v3/<int:id>', main_views.video3, name='v3'),
    path('v4/<int:id>', main_views.video4, name='v4'),
    path('v5/<int:id>', main_views.video5, name='v5'),
    path('p1/<int:cat>', main_views.pricerange1, name='p1'),
    path('p2/<int:cat>', main_views.pricerange2, name='p2'),
    path('p3/<int:cat>', main_views.pricerange3, name='p3'),
    path('s1/', main_views.shop1, name='s1'),
    path('s2/', main_views.shop2, name='s2'),
    path('s3/', main_views.shop3, name='s3'),
    path('courses', main_views.coursepage, name="courses"),
    path('allcourses', main_views.allcoursepage, name="allcourses"),
    path('photography', main_views.photography, name="photography"),
    path('music', main_views.music, name="music"),
    path('paint', main_views.paint, name="paint"),
    path('dance', main_views.dance, name="dance"),
    path('', include('main.urls')),
    path('stripecheck/<int:id>/',main_views.stripecheck,name='stripecheck'),
    path('charge/<int:id>/', main_views.charge, name="charge"),
    path('success', main_views.successMsg, name="success"),
    path('product/<int:id>', main_views.single_product, name='shopitem'),
    path('cart/', include('cart.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='main/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='main/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='main/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='main/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

soad-main/cart/models.py
from django.db import models

# Create your models here.

soad-main/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

soad-main/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from main.models import Product
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm
from . cart import *

def cart_add(request, id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=id) 
    #product = Product.objects.all.get(pk=pid)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request,id=None):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart.html', {'cart': cart})

soad-main/cart/templates/cart/cart.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div style="padding:20px 120px;">
       <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                        </td>
                        <td>{{ product.title }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                              {{ item.update_quantity_form.quantity }}
                              {{ item.update_quantity_form.update }}
                              <input type="submit" value="Update">
                              {% csrf_token %}
                            </form>
                          </td>
                        <td>
                            <a href="{% url 'cart:item_decrement' product.id %}">Remove</a>
                        </td>
                        <td>kshs. {{ item.price }}</td>
                        <td>kshs. {{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr style="background-color: #5AC8FA">
                <td><b>Total</b></td>
                <td colspan="4"></td>
                <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
            </tr>
            </tbody>
        </table> 
    </div>
            
    <div class='tags' style="padding:20px 120px">
        <p class="text-left" style="padding-bottom: 20px;">
            <a href="{% url 'shop' %}" class="btn_3 button-contactForm" style="margin-right: 700px;">Continue Shopping</a>
            <a href="{% url 'order_create' %}" class="btn_3 button-contactForm">Continue to payment</a>
        </p>
    </div>

        </div>
    </div>
{% endblock %}

soad-main/cart/templates/cart/cart_detail.html
{% load cart_tag %}
Total Length :: {{ request.session.cart\length}}

{% for key,value in request.session.cart.items %}
{{ value.price}}
{{ value.title }}

{% endfor %}